# HTC Submit File
# pencilbeam analysis

# Docker container
universe = docker
docker_image = tvwenger/caribou_hi:v1

# Executable
executable = /home/twenger2/tigress_hi/scripts/pencilbeam.sh
arguments = $(Process)

# Data handling
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /home/twenger2/tigress_hi/scripts/pencilbeam.py, /home/twenger2/tigress_hi/data/HI_joint_spectra/$(Process).pkl
transfer_output_remaps = "$(Process)_pencilbeam.pkl = /home/twenger2/tigress_hi/results/HI_joint_spectra_results/$(Process)_pencilbeam.pkl"

# Logging
log = /home/twenger2/tigress_hi/logs/pencilbeam/pencilbeam_$(Cluster)_$(Process).log
error = /home/twenger2/tigress_hi/logs/pencilbeam/pencilbeam_$(Cluster)_$(Process).err
output = /home/twenger2/tigress_hi/logs/pencilbeam/pencilbeam_$(Cluster)_$(Process).out

# Resource request
request_cpus = 8
request_memory = 4GB
request_disk = 128MB

queue 10