# HTC Submit File
# smoothed analysis

# Docker container
universe = docker
docker_image = tvwenger/caribou_hi:v1

# Executable
executable = /home/twenger2/tigress_hi/scripts/smoothed.sh
arguments = $(Process)

# Data handling
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /home/twenger2/tigress_hi/scripts/smoothed.py, /home/twenger2/tigress_hi/data/HI_joint_smooth_spectra/$(Process).pkl
transfer_output_remaps = "$(Process)_smoothed.pkl = /home/twenger2/tigress_hi/results/HI_joint_smooth_spectra_results/$(Process)_smoothed.pkl"

# Logging
log = /home/twenger2/tigress_hi/logs/smoothed/smoothed_$(Cluster)_$(Process).log
error = /home/twenger2/tigress_hi/logs/smoothed/smoothed_$(Cluster)_$(Process).err
output = /home/twenger2/tigress_hi/logs/smoothed/smoothed_$(Cluster)_$(Process).out

# Resource request
request_cpus = 8
request_memory = 4GB
request_disk = 1GB

# 81920 spectra = 80 x 1024
queue 80*1024